# Description of a µ-Services application; parsed by main.py (which would better have been called application.py? ;-)
version: 1
external:
    db:
        - arango-local-1:
            host_name: localhost
            host_port: 8529
            db_name: acasa_db
            app_user: acasa_pyapp
            app_password: Acasa#123
            root_password: Kerber0$
    file:
        - products.db

container:
    asgi: 
    batch:
    wsgi:
        - webportal-1: # TODO change to wsgi/concurrent
            module_py: "web_portal"
            module_cfg:
                host_name: "localhost"
                host_port: 5000
                import_name: "acasa-customer-portal"
                static_folder: "static"
                static_url_path: "/"
                static_host: "localhost"
                template_folder: "templates"
                root_path: "./"
                instance_path: ""
                host_matching: False
                subdomain_matching: False
                instance_relative_config: False
            inject:
                - external.db.arango-local-1