version: 1
quart:
    host_name: "localhost"
    host_port: 5000
    import_name: "acasa-customer-portal"
    static_folder: "static"
    static_url_path: "/"
    static_host: "localhost"
    template_folder: "templates"
    root_path: "./"
    instance_path: ""
    host_matching: False
    subdomain_matching: False
    instance_relative_config: False